version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - back

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD:  root
    volumes:
      - data:/var/lib/mysql
    networks:
      - back

volumes:
  data:
networks:
  back:
